Prevent Building process being stucked in Scilab if a macro fail.
clean-doc renamed clean-help (Sylvestre modif)

Change-Id: If06b84f0c5a3ffae58f92a5925898fe8d01eddca

diff --git a/scilab/Makefile.am b/scilab/Makefile.am
--- a/scilab/Makefile.am
+++ b/scilab/Makefile.am
@@ -2,11 +2,11 @@
 # Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
 # Copyright (C) INRIA - 2006-2008 - Sylvestre Ledru
 # Copyright (C) DIGITEO - 2009 - Sylvestre Ledru
-# 
+#
 # This file must be used under the terms of the CeCILL.
 # This source file is licensed as described in the file COPYING, which
 # you should have received as part of this distribution.  The terms
-# are also available at    
+# are also available at
 # http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
 #
 
@@ -26,14 +26,14 @@ bin_PROGRAMS		= scilab-bin scilab-cli-bin
 
 bin_SCRIPTS			= bin/scilab bin/scilab-adv-cli bin/scilab-cli
 
-scilab_bin_LDFLAGS 		= 
+scilab_bin_LDFLAGS 		=
 scilab_cli_bin_LDFLAGS		=
 
 if IS_MACOSX
 scilab_bin_LDFLAGS 		+= -framework Cocoa
 endif
 
-scilab_bin_CFLAGS 		= -I$(top_srcdir)/modules/io/includes	
+scilab_bin_CFLAGS 		= -I$(top_srcdir)/modules/io/includes
 # --no-undefined --relax
 
 # libshell is mandatory here since main_linux.c depends on it.
@@ -57,12 +57,12 @@ scilab_bin_LDADD 		= $(COMMON_LIBS) $(SCILAB_LIB)
 # Match scilab -nwni (ie command line without graphics)
 scilab_cli_bin_SOURCES	= $(top_srcdir)/modules/shell/src/c/others/mainscic.c
 
-scilab_cli_bin_CFLAGS 		= -DWITHOUT_GUI -I$(top_srcdir)/modules/io/includes	
+scilab_cli_bin_CFLAGS 		= -DWITHOUT_GUI -I$(top_srcdir)/modules/io/includes
 scilab_cli_bin_LDADD 		= $(COMMON_LIBS) $(SCILAB_CLI_LIB)
 
 
 if NEED_JAVA
-# Don't do it for scilab_cli_bin. We want to be able to call it without 
+# Don't do it for scilab_cli_bin. We want to be able to call it without
 # the java libs
 	scilab_bin_LDADD += $(JAVA_JNI_LIBS)
 endif
@@ -165,8 +165,14 @@ if BUILD_HELP
 		cd $(top_builddir);\
 		for l in $(LANGDOC); do \
 			echo "-- Building documentation ($$l) --"; \
-			echo "LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -nouserstartup -e \"xmltojar([],[],'$$l');exit;\"";\
-			LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -l $$l -nouserstartup -e "xmltojar([],[],'$$l');exit;";\
+			COMMAND="try xmltojar([],[],'$$l');catch exit(-1);end;exit(0);"; \
+			echo "LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -nouserstartup -e \"$$COMMAND\"";\
+			LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -l $$l -nouserstartup -e "$$COMMAND";\
+			if test $$? == 0; then\
+				 echo "Done"; \
+			 else \
+				 echo "Failed"; \
+			fi;\
 		done; \
 	else \
 		echo "Cannot find Scilab-adv-cli binary"; \
@@ -181,8 +187,14 @@ if BUILD_HELP
 		cd $(top_builddir);\
 		for l in $(LANGDOC); do \
 			echo "-- Building documentation ($$l) --"; \
-			echo "LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -nouserstartup -e \"xmltoweb([],[],'$$l');exit;\"";\
-			LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -l $$l -nouserstartup -e "xmltoweb([],[],'$$l');exit;";\
+			COMMAND="try xmltoweb([],[],'$$l');catch exit(-1);end;exit(0);";\
+			echo "LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -nouserstartup -e \"$$COMMAND\"";\
+			LANG=C SCI_DISABLE_TK=1 SCI_JAVA_ENABLE_HEADLESS=1 $(top_builddir)/bin/scilab-adv-cli -nb -l $$l -nouserstartup -e "$$COMMAND";\
+			if test $$? == 0; then\
+				 echo "Done"; \
+			 else \
+				 echo "Failed"; \
+			fi;\
 			JAVADOC_TARGET=$(top_builddir)/modules/helptools/web/$$l/javasci; \
 			if test ! -d $$JAVADOC_TARGET; then \
 				mkdir $$JAVADOC_TARGET; \
@@ -200,7 +212,14 @@ check-help:$(top_builddir)/scilab-cli-bin $(top_builddir)/bin/scilab-cli
 	@if test -x $(top_builddir)/scilab-cli-bin; then \
 		for l in $(LANGDOC); do \
 			echo "-- Checking documentation ($$l) --"; \
-			$(top_builddir)/bin/scilab-cli -nb -l $$l -e 'check_help();exit;';\
+			COMMAND="try check_help();catch exit(-1);end;exit(0);";\
+			echo "$(top_builddir)/bin/scilab-cli -nb -l $$l -e \"$$COMMAND\"";\
+			$(top_builddir)/bin/scilab-cli -nb -l $$l -e "$$COMMAND";\
+			if test $$? == 0; then\
+				 echo "Done"; \
+			 else \
+				 echo "Failed"; \
+			fi;\
 		done; \
 	else \
 		echo "Cannot find Scilab binary"; \
@@ -209,7 +228,7 @@ check-help:$(top_builddir)/scilab-cli-bin $(top_builddir)/bin/scilab-cli
 check-recursive: check-local
 check-local:
 	@if test -x $(top_builddir)/scilab-bin; then \
-		COMMAND="test_run();quit";\
+		COMMAND="try test_run();catch exit(-1);end;exit(0)";\
 		export LANG=C;\
 		$(top_builddir)/bin/scilab-adv-cli -nb -e "$$COMMAND"; \
 	else \
@@ -231,7 +250,7 @@ endif
 
 distclean-recursive: distclean-generated clean-recursive
 
-clean-recursive: clean-doc clean-localization clean-macros clean-generated
+clean-recursive: clean-help clean-localization clean-macros clean-generated
 
 clean-macros:
 # Find is necessary because of subdirs...
@@ -242,13 +261,21 @@ clean-macros:
 	echo "-- Cleaning lib files (lib) --"; \
 	find $(top_builddir)/modules/*/macros -name "lib" | xargs --no-run-if-empty rm 2> /dev/null
 
+# To ensure previous compatibility
+clean-doc: clean-help
 
-clean-doc:
+clean-help:
 	-@if test -x $(top_builddir)/scilab-cli-bin; then \
-		echo "$(top_builddir)/bin/scilab-cli -nb -l fr -e 'clean_help();exit;'"; \
-		$(top_builddir)/bin/scilab-cli -nb -l fr -e 'clean_help();exit;'; \
-		echo "$(top_builddir)/bin/scilab-cli  -nb -l en -e 'clean_help();exit;'"; \
-		$(top_builddir)/bin/scilab-cli -nb -l en -e 'clean_help();exit;'; \
+		COMMAND="try clean_help();catch exit(-1);end;exit(0)"; \
+		for l in $(LANGDOC); do \
+			echo "$(top_builddir)/bin/scilab-cli -nb -l $$l -e '$$COMMAND'"; \
+			$(top_builddir)/bin/scilab-cli -nb -l $$l -e "$$COMMAND"; \
+			if test $$? == 0; then\
+				 echo "Done"; \
+			 else \
+				 echo "Failed"; \
+			fi;\
+		done; \
 	else \
 		echo "Cannot find Scilab binary"; \
 	fi; \
@@ -265,7 +292,7 @@ clean-doc:
 
 clean-tests:
 	@if test -x $(top_builddir)/scilab-cli-bin; then \
-		$(top_builddir)/bin/scilab-cli -nb -l fr -e 'test_clean();exit;'; \
+		$(top_builddir)/bin/scilab-cli -nb -l fr -e 'try test_clean();catch exit(-1);end;exit(0);'; \
 	else \
 		echo "Cannot find Scilab binary"; \
 	fi
@@ -276,7 +303,7 @@ clean-localization:
 clean-generated:
 	rm -rf $(top_builddir)/modules/scicos_blocks/build/ 2> /dev/null
 
-distclean-generated: 
+distclean-generated:
 	rm -f $(top_builddir)/modules/core/includes/stack.h 2> /dev/null
 
 
